// Centralized React Icons Provider
// Completely replaces lucide-react with high-performance react-icons

import {
  FiHome,
  FiPlusCircle,
  FiLogIn,
  FiLogOut,
  FiShield,
  FiMoon,
  FiSun,
  FiUser,
  FiSend,
  FiList,
  FiHeart,
  FiSearch,
  FiSliders,
  FiMapPin,
  FiCalendar,
  FiEye,
  FiEyeOff,
  FiCheckCircle,
  FiCopy,
  FiCheck,
  FiShare2,
  FiTrash2,
  FiCamera,
  FiX,
  FiXCircle,
  FiChevronLeft,
  FiChevronRight,
  FiRefreshCw,
  FiDollarSign,
  FiTag,
  FiArrowLeft,
  FiLayers,
  FiAlertTriangle,
  FiAlertCircle,
  FiInfo,
  FiRotateCcw,
  FiExternalLink,
  FiPhone,
  FiLock,
  FiGrid,
  FiClock,
  FiSettings,
  FiMessageSquare,
} from "react-icons/fi";

import {
  FaCrown,
  FaCar,
  FaBuilding,
  FaHouse,
  FaBriefcase,
  FaMicrochip,
  FaBolt,
  FaRegHeart,
  FaTelegram,
  FaCircleCheck,
} from "react-icons/fa6";

import { TbRobot, TbSparkles } from "react-icons/tb";

export {
  FiHome as IconHome,
  FiHome as Home,
  FiPlusCircle as IconPlusCircle,
  FiPlusCircle as PlusCircle,
  FiLogIn as IconLogIn,
  FiLogIn as LogIn,
  FiLogOut as IconLogOut,
  FiLogOut as LogOut,
  FiShield as IconShield,
  FiShield as Shield,
  FiMoon as IconMoon,
  FiMoon as Moon,
  FiSun as IconSun,
  FiSun as Sun,
  FiUser as IconUser,
  FiUser as User,
  FiSend as IconSend,
  FiSend as Send,
  FiList as IconList,
  FiList as List,
  FiHeart as IconHeart,
  FiHeart as Heart,
  FiSearch as IconSearch,
  FiSearch as Search,
  FiSliders as IconSliders,
  FiSliders as Sliders,
  FiMapPin as IconMapPin,
  FiMapPin as MapPin,
  FiCalendar as IconCalendar,
  FiCalendar as Calendar,
  FiEye as IconEye,
  FiEye as Eye,
  FiEyeOff as IconEyeOff,
  FiEyeOff as EyeOff,
  FiCheckCircle as IconCheckCircle,
  FiCheckCircle as CheckCircle2,
  FaCircleCheck as IconCircleCheck,
  FiCopy as IconCopy,
  FiCopy as Copy,
  FiCheck as IconCheck,
  FiCheck as Check,
  FiShare2 as IconShare,
  FiTrash2 as IconTrash,
  FiTrash2 as Trash2,
  FiCamera as IconCamera,
  FiX as IconX,
  FiX as X,
  FiXCircle as IconXCircle,
  FiXCircle as XCircle,
  FiChevronLeft as IconChevronLeft,
  FiChevronRight as IconChevronRight,
  FiRefreshCw as IconRefresh,
  FiRefreshCw as RefreshCw,
  FiDollarSign as IconDollar,
  FiTag as IconTag,
  FiTag as Tag,
  FiArrowLeft as IconArrowLeft,
  FiArrowLeft as ArrowLeft,
  FiLayers as IconLayers,
  FiLayers as Layers,
  FiAlertTriangle as IconAlertTriangle,
  FiAlertTriangle as AlertTriangle,
  FiAlertCircle as IconAlertCircle,
  FiInfo as IconInfo,
  FiInfo as Info,
  FiRotateCcw as IconRotate,
  FiRotateCcw as RotateCcw,
  FiExternalLink as IconExternalLink,
  FiExternalLink as ExternalLink,
  FiPhone as IconPhone,
  FiLock as IconLock,
  FiGrid as IconGrid,
  FiClock as IconClock,
  FiSettings as IconSettings,
  FaCrown as IconCrown,
  FaCrown as Crown,
  FaCar as IconCar,
  FaBuilding as IconBuilding,
  FaHouse as IconHouse,
  FaBriefcase as IconBriefcase,
  FaMicrochip as IconCpu,
  FaBolt as IconZap,
  FaTelegram as IconTelegram,
  TbRobot as IconBot,
  TbRobot as Bot,
  TbSparkles as Sparkles,
  TbSparkles as IconSparkles,
  FiMessageSquare as MessageSquare,
  FiMessageSquare as IconMessageSquare,
};
